src/Entity/Coin.php
<?php

namespace App\Entity;

use App\Repository\CoinRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CoinRepository::class)
 */
class Coin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="float", nullable=true, name="binance_price")
     */
    private $binancePrice;

    /**
     * @ORM\Column(type="float", nullable=true, name="hit_btc_price")
     */
    private $HitBtcPrice;

    /**
     * @ORM\Column(type="float", nullable=true, name="polo_price")
     */
    private $PoloPrice;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $cakePrice;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $bittrexPrice;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $binanceMeta = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $hitMeta = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $percentage;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getBinancePrice(): ?float
    {
        return $this->binancePrice;
    }

    public function setBinancePrice(?float $binancePrice): self
    {
        $this->binancePrice = $binancePrice;

        return $this;
    }

    public function getHitBtcPrice(): ?float
    {
        return $this->HitBtcPrice;
    }

    public function setHitBtcPrice(?float $HitBtcPrice): self
    {
        $this->HitBtcPrice = $HitBtcPrice;

        return $this;
    }

    public function getPoloPrice(): ?float
    {
        return $this->PoloPrice;
    }

    public function setPoloPrice(?float $PoloPrice): self
    {
        $this->PoloPrice = $PoloPrice;

        return $this;
    }

    public function getBinanceMeta(): ?array
    {
        return $this->binanceMeta;
    }

    public function setBinanceMeta(?array $binanceMeta): self
    {
        $this->binanceMeta = $binanceMeta;

        return $this;
    }

    public function getHitMeta(): ?array
    {
        return $this->hitMeta;
    }

    public function setHitMeta(?array $hitMeta): self
    {
        $this->hitMeta = $hitMeta;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBittrexPrice(): ?float
    {
        return $this->bittrexPrice;
    }

    public function setBittrexPrice(?float $bittrexPrice): self
    {
        $this->bittrexPrice = $bittrexPrice;

        return $this;
    }

    public function getPercentage(): ?float
    {
        return $this->percentage;
    }

    public function setPercentage(?float $percentage): self
    {
        $this->percentage = $percentage;

        return $this;
    }

    public function getCakePrice(): ?float
    {
        return $this->cakePrice;
    }

    public function setCakePrice(?float $cakePrice): self
    {
        $this->cakePrice = $cakePrice;

        return $this;
    }
}

src/Controller/ListController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ListController extends AbstractController
{
    /**
     * @Route("/list", name="list")
     *
     * @return Response
     */
    public function index(Request $request)
    {


//        $memcached = new \Memcached();
//        $memcached->addServer("165.22.108.72", 11211);
//        $message = $memcached->get("message");
//        if ($message) {
//            dd($message);
//        } else {
//            $memcached->set("message", "Hello World");
//
//        }
//        var_dump($memcached->getAllKeys());
        //$session = $request->getSession();

         //dd($this->getUser());
        $companies = [
            'Apple' => '$1.16 trillion USD',
            'Samsung' => '$298.68 billion USD',
            'Microsoft' => '$1.10 trillion USD',
            'Alphabet' => '$878.48 billion USD',
            'Intel Corporation' => '$245.82 billion USD',
            'IBM' => '$120.03 billion USD',
            'Facebook' => '$552.39 billion USD',
            'Hon Hai Precision' => '$38.72 billion USD',
            'Tencent' => '$3.02 trillion USD',
            'Oracle' => '$180.54 billion USD',
        ];

        return $this->render('list/index.html.twig', [
            'companies' => $companies,
        ]);
    }

    /**
     * @Route("/test", name="test")
     *
     * @return Response
     */
    public function test(Request $request)
    {
        return new Response('ok');
    }
}

templates/list/index.html.twig
{# templates/list/index.html.twig #} {% extends 'base.html.twig' %} {% block
    body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-light mb-3 mt-3">
                    <div class="card-body">
                        <div class="card-header"></div>



                        <table class="table">
                            <tr>
                                <th>Name</th>
                                <th>Binance</th>
                                <th>HitBtc</th>
                                <th>Polo</th>
                                <td>Deviation</td>
                            </tr>
                            {% for coin in coins %}
                                <tr>
                                    <td>{{ coin.name }}</td>
                                    <td>{{ coin.binancePrice }}</td>
                                    <td>{{ coin.hitBtcPrice }}</td>
                                    <td>{{ coin.poloPrice }}</td>

                                    <td></td>
                                </tr>
                            {% endfor %}
                        </table>

                    </div>
                </div>
                {% if app.user == null %}
                    <a href="{{ path('app_login') }}" class="btn btn-info">
                        You need to login to see the list 😜😜 >></a
                    >
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}